<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Coachs extends \App\Entity\Coachs implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'userCoaches' => [parent::class, 'userCoaches', null],
        "\0".parent::class."\0".'adherants' => [parent::class, 'adherants', null],
        "\0".parent::class."\0".'specialty' => [parent::class, 'specialty', null],
        "\0".parent::class."\0".'trainingSessions' => [parent::class, 'trainingSessions', null],
        "\0".'App\\Entity\\Users'."\0".'Imcs' => ['App\\Entity\\Users', 'Imcs', null],
        "\0".'App\\Entity\\Users'."\0".'coachCoaches' => ['App\\Entity\\Users', 'coachCoaches', null],
        "\0".'App\\Entity\\Users'."\0".'createdAt' => ['App\\Entity\\Users', 'createdAt', null],
        "\0".'App\\Entity\\Users'."\0".'email' => ['App\\Entity\\Users', 'email', null],
        "\0".'App\\Entity\\Users'."\0".'id' => ['App\\Entity\\Users', 'id', null],
        "\0".'App\\Entity\\Users'."\0".'name' => ['App\\Entity\\Users', 'name', null],
        "\0".'App\\Entity\\Users'."\0".'password' => ['App\\Entity\\Users', 'password', null],
        "\0".'App\\Entity\\Users'."\0".'receivedMessages' => ['App\\Entity\\Users', 'receivedMessages', null],
        "\0".'App\\Entity\\Users'."\0".'roles' => ['App\\Entity\\Users', 'roles', null],
        "\0".'App\\Entity\\Users'."\0".'sentMessages' => ['App\\Entity\\Users', 'sentMessages', null],
        "\0".'App\\Entity\\Users'."\0".'updatedAt' => ['App\\Entity\\Users', 'updatedAt', null],
        'Imcs' => ['App\\Entity\\Users', 'Imcs', null],
        'adherants' => [parent::class, 'adherants', null],
        'coachCoaches' => ['App\\Entity\\Users', 'coachCoaches', null],
        'createdAt' => ['App\\Entity\\Users', 'createdAt', null],
        'email' => ['App\\Entity\\Users', 'email', null],
        'id' => ['App\\Entity\\Users', 'id', null],
        'name' => ['App\\Entity\\Users', 'name', null],
        'password' => ['App\\Entity\\Users', 'password', null],
        'receivedMessages' => ['App\\Entity\\Users', 'receivedMessages', null],
        'roles' => ['App\\Entity\\Users', 'roles', null],
        'sentMessages' => ['App\\Entity\\Users', 'sentMessages', null],
        'specialty' => [parent::class, 'specialty', null],
        'trainingSessions' => [parent::class, 'trainingSessions', null],
        'updatedAt' => ['App\\Entity\\Users', 'updatedAt', null],
        'userCoaches' => [parent::class, 'userCoaches', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
