controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
easy_admin_bundle:
    resource: '../vendor/easycorp/easyadmin-bundle/src/Controller/'
    type: annotation
