<?php

namespace Container5lu7T45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ad6ib6oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ad6ib6o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ad6ib6o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trainingSessionRepo' => ['privates', 'App\\Repository\\TrainingSessionRepository', 'getTrainingSessionRepositoryService', true],
        ], [
            'trainingSessionRepo' => 'App\\Repository\\TrainingSessionRepository',
        ]);
    }
}
