<?php

namespace Container5lu7T45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R7yS59fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R7yS59f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R7yS59f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'schedulerRepository' => ['privates', 'App\\Repository\\SchedulerRepository', 'getSchedulerRepositoryService', true],
        ], [
            'schedulerRepository' => 'App\\Repository\\SchedulerRepository',
        ]);
    }
}
