<?php

namespace Container5lu7T45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pi9uj0rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Pi9uj0r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Pi9uj0r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'administrator' => ['privates', 'App\\Entity\\Administrators', 'getAdministratorsService', true],
        ], [
            'administrator' => 'App\\Entity\\Administrators',
        ]);
    }
}
