<?php

namespace Container5lu7T45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G0RL2ECService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g0RL2EC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g0RL2EC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'abonnement' => ['privates', 'App\\Entity\\Abonnements', 'getAbonnementsService', true],
        ], [
            'abonnement' => 'App\\Entity\\Abonnements',
        ]);
    }
}
