<?php

namespace Container5lu7T45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WEdnUIFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wEdnUIF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wEdnUIF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'administratorRepository' => ['privates', 'App\\Repository\\AdministratorsRepository', 'getAdministratorsRepositoryService', true],
            'coachRepository' => ['privates', 'App\\Repository\\CoachsRepository', 'getCoachsRepositoryService', true],
            'machineRepository' => ['privates', 'App\\Repository\\MachinesRepository', 'getMachinesRepositoryService', true],
            'schedulerRepository' => ['privates', 'App\\Repository\\SchedulerRepository', 'getSchedulerRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'administratorRepository' => 'App\\Repository\\AdministratorsRepository',
            'coachRepository' => 'App\\Repository\\CoachsRepository',
            'machineRepository' => 'App\\Repository\\MachinesRepository',
            'schedulerRepository' => 'App\\Repository\\SchedulerRepository',
            'userRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
