<?php

namespace Container5lu7T45;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Messageries' shared autowired service.
     *
     * @return \App\Entity\Messageries
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'Messageries.php';

        return $container->privates['App\\Entity\\Messageries'] = new \App\Entity\Messageries();
    }
}
